version: '3'
services:
  go-service:
    build: ./go-service-pr9
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - go-service